### ISSUE TITLE
Some things are missing.

### ISSUE THREAD

**Issue by ZeroDot1** [pfbrowning/ng-radio#1]
- `(??)` Add multilingual support.
- `(In progress)` Add asynchronous functions to the HTML pages to make the pages faster. 
- `(Coming soon)` Add all required steps to the readme file needed to use the app on a server with Linux and Windows.
- `(In progress)` Add a topbar with the name of the app and a logo.

I like the idea, and the project has been very well-made so far.
Keep up the good work!

**Comment by pfbrowning** [comment]
Thanks for the feedback!  It's good to know that somebody's paying attention and appreciates the work I'm putting into this.

This is an incomplete hobby project under active development in what little free time I have available.  Therefore you can expect it to evolve quite a bit from where it is now, but not quickly.

- Multilingual support is not something that I had planned on implementing.  I would welcome pull requests if somebody would like to implement this themselves, but I would recommend doing so once the project is closer to completion, because the content might change quite a bit from where it is now.
- I'm not quite sure what you mean by 'Add asynchronous functions to the HTML pages to make the pages faster'.
- I definitely intend to write a readme once I've gotten the core functionality implemented.
- If you use the app on a small screen, you'll notice that there is a topbar with the app name and a hamburger menu.  This is intentionally hidden when the screen is larger than 800px, in favor of the sidebar which also shows the app name.
- I don't have a logo yet, but I would welcome pull requests if anybody wants to make one.

**Comment by ZeroDot1** [comment]
`I don't have a logo yet, but I would welcome pull requests if anybody wants to make one.`
@pfbrowning I designed a logo for you.
![NG-Radio](https://user-images.githubusercontent.com/28985171/57586256-965c0a00-74f3-11e9-9b8a-72750141d8d5.png)

**Comment by pfbrowning** [comment]
@ZeroDot1 Thank you for this!

Could you draft something up with the name "Browninglogic Radio" (rather than "NG-Radio")?  I'd like to pick one name for the app and stick with it throughout the application.  I'm partial to "Browninglogic Radio" because it sounds less generic and, more importantly, [ng-radio](https://www.npmjs.com/package/ng-radio) is already taken by something else.

In the meantime I've added the provided logo in the ng-radio-logo branch:
![image](https://user-images.githubusercontent.com/25021610/57744742-787bda00-7698-11e9-8247-b3014faac85f.png)

What do you think?  Admittedly I'm not a graphic designer, but I feel like it's missing something and I can't place my finger on what.

**Comment by ZeroDot1** [comment]
Hi @pfbrowning,
I'm not a graphic designer but I like to do it.
I created a new logo, that should match now.
I made a smiley out of the I-point to make the logo even more unique. 
![Logo_new_BLR](https://user-images.githubusercontent.com/28985171/57958763-32757f00-7901-11e9-9777-1c9350f34b1e.png)
I think we could adjust the CSS to the page, at the moment it doesn't look so good with the colors.
Take a look at my homepage https://zerodot1.gitlab.io/CoinBlockerListsWeb/index.html , we should use darker colors for Browninglogic Radio.
Because not one radio site has dark colors, another reason is that many people listen to radio at night, and then a dark page interface is very welcome.

**Comment by ZeroDot1** [comment]
Hi @pfbrowning,
Can you add the async function as shown on the screenshot?
![Bildschirmfoto vom 2019-05-18 00-47-32](https://user-images.githubusercontent.com/28985171/57960064-0fe66480-7907-11e9-8fec-370ef2310d00.png)

This makes the scripts load faster and the load times shorter.
It is important to set async before the script so that it can be used correctly by the browser.

For the CSS I have already made a pull request, in which you can find the appropriate example so that the CSS can be loaded asynchronously.

**Comment by ZeroDot1** [comment]
Hi @pfbrowning, Another change is to add a focus function for the first input field in the radio browser so that the user can start the search directly without having to click into the search field.
Screenshot:
![Bildschirmfoto vom 2019-05-18 00-59-19](https://user-images.githubusercontent.com/28985171/57960298-3eb10a80-7908-11e9-849e-62bfc3eb5b6a.png)
HTML Example:
`<input required="required" autocomplete="off" autofocus readonly onfocus="this.removeAttribute('readonly');" type="text"
`
By the way, if you implement this exactly as in the example, accidental inputs will be prevented and the load on the server will be reduced.

**Comment by pfbrowning** [comment]
@ZeroDot1 My availability to work on this project will be very limited at least for the next few weeks because I've got more urgent stuff to take care of in what little free time I have.  I'll take a look through all of this when I have more time to put into it.

Also, in the future, for the sake of organizational clarity and ease of discussion, could you please open a new "Issue" for each individual request / suggestion?

**Comment by pfbrowning** [comment]
- **Colors** - I'm pretty happy with the colors as they are now.  I'm using the default Indigo / Pink Angular Material theme because I like the way it looks out of the box.  I carefully selected the shade of teal that I'm using for the sidebar because I needed a "Secondary" color to compliment the "Primary" indigo.
- **Logo** - I'm sorry, but I don't think those logos are the aesthetic that I'm looking for.  I have a graphic designer friend who put together a few sketches that I liked.  I'm thinking about hiring her to put something together for me when she has the availability.  In the meantime, I think it looks just fine with the text-based "Browninglogic Radio" header.  The logo is a very low priority for me.  If you'd like to have a go at it, here are the sketches that I liked:
![image](https://user-images.githubusercontent.com/25021610/58394802-16fe2880-8013-11e9-9062-a8da2633e618.png)
- **Scripts** - Where are the script tags that you want 'async' added to?  There are no scripts being loaded in the head, and I don't want to mess around with the loading of the Angular CLI bundles.
- **Autofocus** - Apparently autofocus doesn't work well with MatInput, so I'm programmatically focusing the relevant inputs on ngOnInit in the custom-station and radio-browser components.

I'm closing this ticket because it's become a catch-all, which is obviously quite messy.  If you'd like to continue discussion on any of these items, please open a separate issue for each topic.
