### ISSUE TITLE
Add a lyrics function

### ISSUE THREAD

**Issue by ZeroDot1** [pfbrowning/ng-radio#4]
Hi @pfbrowning,
Is it possible to add a lyrics function to Now Playing?
So you only have to click a button to display the lyrics of the currently played song directly on the Now Playing page.

You could make it so that the information for the lyrics from the ID3 which comes directly from the radio can search for the matching lyrics.

**Comment by pfbrowning** [comment]
@ZeroDot1 I agree that this is a cool idea for a new feature, but in the grand scheme of things it's a low priority for me.  In order to clarify what my intentions and priorities are for this app, I've added a roadmap to the readme.

If you want to implement yourself and submit a PR, you're welcome to do so, but in general I'd prefer to prioritize the things that I've listed in the roadmap and in the "Down the Road" list.
